
import { Inter } from "next/font/google";
import "animate.css";
import "./globals.css";
// import "./theme.min.css"
import "bootstrap/dist/css/bootstrap.css";
import BootstrapClient from "./_components/BootstrapClients";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { store } from "@/store";
import Providers from "@/reduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rentals Pool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body >
          <Header />
          {children}
          <BootstrapClient />
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
